// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/mesh/v1/mesh.proto

// Package mesh.v1 is the typed, versioned agent protocol. Breaking changes get
// a new major version (mesh/v2); v1 is never broken in place (CLAUDE.md).

package meshv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeshService_RegisterAgent_FullMethodName    = "/mesh.v1.MeshService/RegisterAgent"
	MeshService_CreateWorkspace_FullMethodName  = "/mesh.v1.MeshService/CreateWorkspace"
	MeshService_ListWorkspaces_FullMethodName   = "/mesh.v1.MeshService/ListWorkspaces"
	MeshService_FinishWorkspace_FullMethodName  = "/mesh.v1.MeshService/FinishWorkspace"
	MeshService_DeleteWorkspace_FullMethodName  = "/mesh.v1.MeshService/DeleteWorkspace"
	MeshService_ReclaimWorktrees_FullMethodName = "/mesh.v1.MeshService/ReclaimWorktrees"
	MeshService_CheckIntent_FullMethodName      = "/mesh.v1.MeshService/CheckIntent"
	MeshService_RegisterIntent_FullMethodName   = "/mesh.v1.MeshService/RegisterIntent"
	MeshService_SubmitPR_FullMethodName         = "/mesh.v1.MeshService/SubmitPR"
	MeshService_ListPRs_FullMethodName          = "/mesh.v1.MeshService/ListPRs"
)

// MeshServiceClient is the client API for MeshService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MeshService is the surface agents and the CLI use to drive the daemon. RPCs
// that can yield more than one result stream, so clients render progressively.
type MeshServiceClient interface {
	// RegisterAgent registers (or re-registers) an agent. Idempotent.
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	// CreateWorkspace provisions an isolated worktree-backed workspace.
	CreateWorkspace(ctx context.Context, in *CreateWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error)
	// ListWorkspaces streams every workspace in creation order.
	ListWorkspaces(ctx context.Context, in *ListWorkspacesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Workspace], error)
	// FinishWorkspace marks a workspace terminal and reclaims its worktree.
	FinishWorkspace(ctx context.Context, in *FinishWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error)
	// DeleteWorkspace removes a workspace and its worktree entirely.
	DeleteWorkspace(ctx context.Context, in *DeleteWorkspaceRequest, opts ...grpc.CallOption) (*DeleteWorkspaceResponse, error)
	// ReclaimWorktrees streams the names of orphan worktrees it reclaimed.
	ReclaimWorktrees(ctx context.Context, in *ReclaimWorktreesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReclaimedWorktree], error)
	// CheckIntent reports overlap against active intents without recording one.
	CheckIntent(ctx context.Context, in *CheckIntentRequest, opts ...grpc.CallOption) (*Decision, error)
	// RegisterIntent records an intent and returns the overlap decision.
	RegisterIntent(ctx context.Context, in *RegisterIntentRequest, opts ...grpc.CallOption) (*RegisterIntentResponse, error)
	// SubmitPR enqueues a pull request for a workspace branch.
	SubmitPR(ctx context.Context, in *SubmitPRRequest, opts ...grpc.CallOption) (*PullRequest, error)
	// ListPRs streams queued PRs filtered by status.
	ListPRs(ctx context.Context, in *ListPRsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullRequest], error)
}

type meshServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeshServiceClient(cc grpc.ClientConnInterface) MeshServiceClient {
	return &meshServiceClient{cc}
}

func (c *meshServiceClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, MeshService_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) CreateWorkspace(ctx context.Context, in *CreateWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workspace)
	err := c.cc.Invoke(ctx, MeshService_CreateWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) ListWorkspaces(ctx context.Context, in *ListWorkspacesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Workspace], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MeshService_ServiceDesc.Streams[0], MeshService_ListWorkspaces_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListWorkspacesRequest, Workspace]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeshService_ListWorkspacesClient = grpc.ServerStreamingClient[Workspace]

func (c *meshServiceClient) FinishWorkspace(ctx context.Context, in *FinishWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workspace)
	err := c.cc.Invoke(ctx, MeshService_FinishWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) DeleteWorkspace(ctx context.Context, in *DeleteWorkspaceRequest, opts ...grpc.CallOption) (*DeleteWorkspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWorkspaceResponse)
	err := c.cc.Invoke(ctx, MeshService_DeleteWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) ReclaimWorktrees(ctx context.Context, in *ReclaimWorktreesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReclaimedWorktree], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MeshService_ServiceDesc.Streams[1], MeshService_ReclaimWorktrees_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReclaimWorktreesRequest, ReclaimedWorktree]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeshService_ReclaimWorktreesClient = grpc.ServerStreamingClient[ReclaimedWorktree]

func (c *meshServiceClient) CheckIntent(ctx context.Context, in *CheckIntentRequest, opts ...grpc.CallOption) (*Decision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Decision)
	err := c.cc.Invoke(ctx, MeshService_CheckIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) RegisterIntent(ctx context.Context, in *RegisterIntentRequest, opts ...grpc.CallOption) (*RegisterIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterIntentResponse)
	err := c.cc.Invoke(ctx, MeshService_RegisterIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) SubmitPR(ctx context.Context, in *SubmitPRRequest, opts ...grpc.CallOption) (*PullRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullRequest)
	err := c.cc.Invoke(ctx, MeshService_SubmitPR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) ListPRs(ctx context.Context, in *ListPRsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MeshService_ServiceDesc.Streams[2], MeshService_ListPRs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListPRsRequest, PullRequest]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeshService_ListPRsClient = grpc.ServerStreamingClient[PullRequest]

// MeshServiceServer is the server API for MeshService service.
// All implementations must embed UnimplementedMeshServiceServer
// for forward compatibility.
//
// MeshService is the surface agents and the CLI use to drive the daemon. RPCs
// that can yield more than one result stream, so clients render progressively.
type MeshServiceServer interface {
	// RegisterAgent registers (or re-registers) an agent. Idempotent.
	RegisterAgent(context.Context, *RegisterAgentRequest) (*Agent, error)
	// CreateWorkspace provisions an isolated worktree-backed workspace.
	CreateWorkspace(context.Context, *CreateWorkspaceRequest) (*Workspace, error)
	// ListWorkspaces streams every workspace in creation order.
	ListWorkspaces(*ListWorkspacesRequest, grpc.ServerStreamingServer[Workspace]) error
	// FinishWorkspace marks a workspace terminal and reclaims its worktree.
	FinishWorkspace(context.Context, *FinishWorkspaceRequest) (*Workspace, error)
	// DeleteWorkspace removes a workspace and its worktree entirely.
	DeleteWorkspace(context.Context, *DeleteWorkspaceRequest) (*DeleteWorkspaceResponse, error)
	// ReclaimWorktrees streams the names of orphan worktrees it reclaimed.
	ReclaimWorktrees(*ReclaimWorktreesRequest, grpc.ServerStreamingServer[ReclaimedWorktree]) error
	// CheckIntent reports overlap against active intents without recording one.
	CheckIntent(context.Context, *CheckIntentRequest) (*Decision, error)
	// RegisterIntent records an intent and returns the overlap decision.
	RegisterIntent(context.Context, *RegisterIntentRequest) (*RegisterIntentResponse, error)
	// SubmitPR enqueues a pull request for a workspace branch.
	SubmitPR(context.Context, *SubmitPRRequest) (*PullRequest, error)
	// ListPRs streams queued PRs filtered by status.
	ListPRs(*ListPRsRequest, grpc.ServerStreamingServer[PullRequest]) error
	mustEmbedUnimplementedMeshServiceServer()
}

// UnimplementedMeshServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeshServiceServer struct{}

func (UnimplementedMeshServiceServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*Agent, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedMeshServiceServer) CreateWorkspace(context.Context, *CreateWorkspaceRequest) (*Workspace, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkspace not implemented")
}
func (UnimplementedMeshServiceServer) ListWorkspaces(*ListWorkspacesRequest, grpc.ServerStreamingServer[Workspace]) error {
	return status.Error(codes.Unimplemented, "method ListWorkspaces not implemented")
}
func (UnimplementedMeshServiceServer) FinishWorkspace(context.Context, *FinishWorkspaceRequest) (*Workspace, error) {
	return nil, status.Error(codes.Unimplemented, "method FinishWorkspace not implemented")
}
func (UnimplementedMeshServiceServer) DeleteWorkspace(context.Context, *DeleteWorkspaceRequest) (*DeleteWorkspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWorkspace not implemented")
}
func (UnimplementedMeshServiceServer) ReclaimWorktrees(*ReclaimWorktreesRequest, grpc.ServerStreamingServer[ReclaimedWorktree]) error {
	return status.Error(codes.Unimplemented, "method ReclaimWorktrees not implemented")
}
func (UnimplementedMeshServiceServer) CheckIntent(context.Context, *CheckIntentRequest) (*Decision, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckIntent not implemented")
}
func (UnimplementedMeshServiceServer) RegisterIntent(context.Context, *RegisterIntentRequest) (*RegisterIntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterIntent not implemented")
}
func (UnimplementedMeshServiceServer) SubmitPR(context.Context, *SubmitPRRequest) (*PullRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitPR not implemented")
}
func (UnimplementedMeshServiceServer) ListPRs(*ListPRsRequest, grpc.ServerStreamingServer[PullRequest]) error {
	return status.Error(codes.Unimplemented, "method ListPRs not implemented")
}
func (UnimplementedMeshServiceServer) mustEmbedUnimplementedMeshServiceServer() {}
func (UnimplementedMeshServiceServer) testEmbeddedByValue()                     {}

// UnsafeMeshServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeshServiceServer will
// result in compilation errors.
type UnsafeMeshServiceServer interface {
	mustEmbedUnimplementedMeshServiceServer()
}

func RegisterMeshServiceServer(s grpc.ServiceRegistrar, srv MeshServiceServer) {
	// If the following call panics, it indicates UnimplementedMeshServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeshService_ServiceDesc, srv)
}

func _MeshService_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_CreateWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).CreateWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_CreateWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).CreateWorkspace(ctx, req.(*CreateWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_ListWorkspaces_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListWorkspacesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MeshServiceServer).ListWorkspaces(m, &grpc.GenericServerStream[ListWorkspacesRequest, Workspace]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeshService_ListWorkspacesServer = grpc.ServerStreamingServer[Workspace]

func _MeshService_FinishWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).FinishWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_FinishWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).FinishWorkspace(ctx, req.(*FinishWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_DeleteWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).DeleteWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_DeleteWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).DeleteWorkspace(ctx, req.(*DeleteWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_ReclaimWorktrees_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReclaimWorktreesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MeshServiceServer).ReclaimWorktrees(m, &grpc.GenericServerStream[ReclaimWorktreesRequest, ReclaimedWorktree]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeshService_ReclaimWorktreesServer = grpc.ServerStreamingServer[ReclaimedWorktree]

func _MeshService_CheckIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).CheckIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_CheckIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).CheckIntent(ctx, req.(*CheckIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_RegisterIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).RegisterIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_RegisterIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).RegisterIntent(ctx, req.(*RegisterIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_SubmitPR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitPRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).SubmitPR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_SubmitPR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).SubmitPR(ctx, req.(*SubmitPRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_ListPRs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListPRsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MeshServiceServer).ListPRs(m, &grpc.GenericServerStream[ListPRsRequest, PullRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeshService_ListPRsServer = grpc.ServerStreamingServer[PullRequest]

// MeshService_ServiceDesc is the grpc.ServiceDesc for MeshService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeshService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mesh.v1.MeshService",
	HandlerType: (*MeshServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _MeshService_RegisterAgent_Handler,
		},
		{
			MethodName: "CreateWorkspace",
			Handler:    _MeshService_CreateWorkspace_Handler,
		},
		{
			MethodName: "FinishWorkspace",
			Handler:    _MeshService_FinishWorkspace_Handler,
		},
		{
			MethodName: "DeleteWorkspace",
			Handler:    _MeshService_DeleteWorkspace_Handler,
		},
		{
			MethodName: "CheckIntent",
			Handler:    _MeshService_CheckIntent_Handler,
		},
		{
			MethodName: "RegisterIntent",
			Handler:    _MeshService_RegisterIntent_Handler,
		},
		{
			MethodName: "SubmitPR",
			Handler:    _MeshService_SubmitPR_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListWorkspaces",
			Handler:       _MeshService_ListWorkspaces_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReclaimWorktrees",
			Handler:       _MeshService_ReclaimWorktrees_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListPRs",
			Handler:       _MeshService_ListPRs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mesh/v1/mesh.proto",
}
