// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/mesh/v1/mesh.proto

// Package mesh.v1 is the typed, versioned agent protocol. Breaking changes get
// a new major version (mesh/v2); v1 is never broken in place (CLAUDE.md).

package meshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkspaceStatus mirrors the workspace lifecycle.
type WorkspaceStatus int32

const (
	WorkspaceStatus_WORKSPACE_STATUS_UNSPECIFIED WorkspaceStatus = 0
	WorkspaceStatus_WORKSPACE_STATUS_ACTIVE      WorkspaceStatus = 1
	WorkspaceStatus_WORKSPACE_STATUS_DONE        WorkspaceStatus = 2
	WorkspaceStatus_WORKSPACE_STATUS_ERROR       WorkspaceStatus = 3
)

// Enum value maps for WorkspaceStatus.
var (
	WorkspaceStatus_name = map[int32]string{
		0: "WORKSPACE_STATUS_UNSPECIFIED",
		1: "WORKSPACE_STATUS_ACTIVE",
		2: "WORKSPACE_STATUS_DONE",
		3: "WORKSPACE_STATUS_ERROR",
	}
	WorkspaceStatus_value = map[string]int32{
		"WORKSPACE_STATUS_UNSPECIFIED": 0,
		"WORKSPACE_STATUS_ACTIVE":      1,
		"WORKSPACE_STATUS_DONE":        2,
		"WORKSPACE_STATUS_ERROR":       3,
	}
)

func (x WorkspaceStatus) Enum() *WorkspaceStatus {
	p := new(WorkspaceStatus)
	*p = x
	return p
}

func (x WorkspaceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkspaceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mesh_v1_mesh_proto_enumTypes[0].Descriptor()
}

func (WorkspaceStatus) Type() protoreflect.EnumType {
	return &file_proto_mesh_v1_mesh_proto_enumTypes[0]
}

func (x WorkspaceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkspaceStatus.Descriptor instead.
func (WorkspaceStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{0}
}

// Verdict is the outcome of an intent check.
type Verdict int32

const (
	Verdict_VERDICT_UNSPECIFIED Verdict = 0
	Verdict_VERDICT_CLEAR       Verdict = 1
	Verdict_VERDICT_WARN        Verdict = 2
)

// Enum value maps for Verdict.
var (
	Verdict_name = map[int32]string{
		0: "VERDICT_UNSPECIFIED",
		1: "VERDICT_CLEAR",
		2: "VERDICT_WARN",
	}
	Verdict_value = map[string]int32{
		"VERDICT_UNSPECIFIED": 0,
		"VERDICT_CLEAR":       1,
		"VERDICT_WARN":        2,
	}
)

func (x Verdict) Enum() *Verdict {
	p := new(Verdict)
	*p = x
	return p
}

func (x Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mesh_v1_mesh_proto_enumTypes[1].Descriptor()
}

func (Verdict) Type() protoreflect.EnumType {
	return &file_proto_mesh_v1_mesh_proto_enumTypes[1]
}

func (x Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict.Descriptor instead.
func (Verdict) EnumDescriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{1}
}

// PRStatus mirrors the PR queue lifecycle.
type PRStatus int32

const (
	PRStatus_PR_STATUS_UNSPECIFIED PRStatus = 0
	PRStatus_PR_STATUS_QUEUED      PRStatus = 1
	PRStatus_PR_STATUS_SUBMITTED   PRStatus = 2
	PRStatus_PR_STATUS_MERGED      PRStatus = 3
	PRStatus_PR_STATUS_FAILED      PRStatus = 4
)

// Enum value maps for PRStatus.
var (
	PRStatus_name = map[int32]string{
		0: "PR_STATUS_UNSPECIFIED",
		1: "PR_STATUS_QUEUED",
		2: "PR_STATUS_SUBMITTED",
		3: "PR_STATUS_MERGED",
		4: "PR_STATUS_FAILED",
	}
	PRStatus_value = map[string]int32{
		"PR_STATUS_UNSPECIFIED": 0,
		"PR_STATUS_QUEUED":      1,
		"PR_STATUS_SUBMITTED":   2,
		"PR_STATUS_MERGED":      3,
		"PR_STATUS_FAILED":      4,
	}
)

func (x PRStatus) Enum() *PRStatus {
	p := new(PRStatus)
	*p = x
	return p
}

func (x PRStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PRStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mesh_v1_mesh_proto_enumTypes[2].Descriptor()
}

func (PRStatus) Type() protoreflect.EnumType {
	return &file_proto_mesh_v1_mesh_proto_enumTypes[2]
}

func (x PRStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PRStatus.Descriptor instead.
func (PRStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{2}
}

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Workspace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Status        WorkspaceStatus        `protobuf:"varint,5,opt,name=status,proto3,enum=mesh.v1.WorkspaceStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *Workspace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workspace) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Workspace) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Workspace) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Workspace) GetStatus() WorkspaceStatus {
	if x != nil {
		return x.Status
	}
	return WorkspaceStatus_WORKSPACE_STATUS_UNSPECIFIED
}

type CreateWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkspaceRequest) Reset() {
	*x = CreateWorkspaceRequest{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceRequest) ProtoMessage() {}

func (x *CreateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWorkspaceRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ListWorkspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesRequest) Reset() {
	*x = ListWorkspacesRequest{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesRequest) ProtoMessage() {}

func (x *ListWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*ListWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{4}
}

type FinishWorkspaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// When true the workspace is finished as errored rather than done.
	Errored       bool `protobuf:"varint,2,opt,name=errored,proto3" json:"errored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishWorkspaceRequest) Reset() {
	*x = FinishWorkspaceRequest{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishWorkspaceRequest) ProtoMessage() {}

func (x *FinishWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*FinishWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{5}
}

func (x *FinishWorkspaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FinishWorkspaceRequest) GetErrored() bool {
	if x != nil {
		return x.Errored
	}
	return false
}

type DeleteWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceRequest) Reset() {
	*x = DeleteWorkspaceRequest{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceRequest) ProtoMessage() {}

func (x *DeleteWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteWorkspaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceResponse) Reset() {
	*x = DeleteWorkspaceResponse{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceResponse) ProtoMessage() {}

func (x *DeleteWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{7}
}

type ReclaimWorktreesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReclaimWorktreesRequest) Reset() {
	*x = ReclaimWorktreesRequest{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReclaimWorktreesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReclaimWorktreesRequest) ProtoMessage() {}

func (x *ReclaimWorktreesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReclaimWorktreesRequest.ProtoReflect.Descriptor instead.
func (*ReclaimWorktreesRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{8}
}

type ReclaimedWorktree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReclaimedWorktree) Reset() {
	*x = ReclaimedWorktree{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReclaimedWorktree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReclaimedWorktree) ProtoMessage() {}

func (x *ReclaimedWorktree) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReclaimedWorktree.ProtoReflect.Descriptor instead.
func (*ReclaimedWorktree) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{9}
}

func (x *ReclaimedWorktree) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Conflict is an overlap with one other workspace's active intent.
type Conflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Paths         []string               `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conflict) Reset() {
	*x = Conflict{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conflict) ProtoMessage() {}

func (x *Conflict) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conflict.ProtoReflect.Descriptor instead.
func (*Conflict) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{10}
}

func (x *Conflict) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Conflict) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type Decision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdict       Verdict                `protobuf:"varint,1,opt,name=verdict,proto3,enum=mesh.v1.Verdict" json:"verdict,omitempty"`
	Conflicts     []*Conflict            `protobuf:"bytes,2,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{11}
}

func (x *Decision) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *Decision) GetConflicts() []*Conflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

type CheckIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Files         []string               `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIntentRequest) Reset() {
	*x = CheckIntentRequest{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIntentRequest) ProtoMessage() {}

func (x *CheckIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIntentRequest.ProtoReflect.Descriptor instead.
func (*CheckIntentRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{12}
}

func (x *CheckIntentRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CheckIntentRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

type RegisterIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Files         []string               `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterIntentRequest) Reset() {
	*x = RegisterIntentRequest{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterIntentRequest) ProtoMessage() {}

func (x *RegisterIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterIntentRequest.ProtoReflect.Descriptor instead.
func (*RegisterIntentRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterIntentRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *RegisterIntentRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

type RegisterIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntentId      string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	Decision      *Decision              `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterIntentResponse) Reset() {
	*x = RegisterIntentResponse{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterIntentResponse) ProtoMessage() {}

func (x *RegisterIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterIntentResponse.ProtoReflect.Descriptor instead.
func (*RegisterIntentResponse) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterIntentResponse) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *RegisterIntentResponse) GetDecision() *Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

type PullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Status        PRStatus               `protobuf:"varint,6,opt,name=status,proto3,enum=mesh.v1.PRStatus" json:"status,omitempty"`
	Attempts      int32                  `protobuf:"varint,7,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{15}
}

func (x *PullRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PullRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *PullRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *PullRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PullRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PullRequest) GetStatus() PRStatus {
	if x != nil {
		return x.Status
	}
	return PRStatus_PR_STATUS_UNSPECIFIED
}

func (x *PullRequest) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

type SubmitPRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPRRequest) Reset() {
	*x = SubmitPRRequest{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPRRequest) ProtoMessage() {}

func (x *SubmitPRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPRRequest.ProtoReflect.Descriptor instead.
func (*SubmitPRRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{16}
}

func (x *SubmitPRRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SubmitPRRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *SubmitPRRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SubmitPRRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type ListPRsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        PRStatus               `protobuf:"varint,1,opt,name=status,proto3,enum=mesh.v1.PRStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPRsRequest) Reset() {
	*x = ListPRsRequest{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPRsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPRsRequest) ProtoMessage() {}

func (x *ListPRsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPRsRequest.ProtoReflect.Descriptor instead.
func (*ListPRsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{17}
}

func (x *ListPRsRequest) GetStatus() PRStatus {
	if x != nil {
		return x.Status
	}
	return PRStatus_PR_STATUS_UNSPECIFIED
}

type PlanTrainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanTrainsRequest) Reset() {
	*x = PlanTrainsRequest{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanTrainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanTrainsRequest) ProtoMessage() {}

func (x *PlanTrainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanTrainsRequest.ProtoReflect.Descriptor instead.
func (*PlanTrainsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{18}
}

// A Train is a batch of PRs that can land together without conflicting.
type Train struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prs           []*PullRequest         `protobuf:"bytes,1,rep,name=prs,proto3" json:"prs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Train) Reset() {
	*x = Train{}
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Train) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Train) ProtoMessage() {}

func (x *Train) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_v1_mesh_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Train.ProtoReflect.Descriptor instead.
func (*Train) Descriptor() ([]byte, []int) {
	return file_proto_mesh_v1_mesh_proto_rawDescGZIP(), []int{19}
}

func (x *Train) GetPrs() []*PullRequest {
	if x != nil {
		return x.Prs
	}
	return nil
}

var File_proto_mesh_v1_mesh_proto protoreflect.FileDescriptor

const file_proto_mesh_v1_mesh_proto_rawDesc = "" +
	"\n" +
	"\x18proto/mesh/v1/mesh.proto\x12\amesh.v1\"+\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\":\n" +
	"\x14RegisterAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x94\x01\n" +
	"\tWorkspace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x120\n" +
	"\x06status\x18\x05 \x01(\x0e2\x18.mesh.v1.WorkspaceStatusR\x06status\"3\n" +
	"\x16CreateWorkspaceRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x17\n" +
	"\x15ListWorkspacesRequest\"B\n" +
	"\x16FinishWorkspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aerrored\x18\x02 \x01(\bR\aerrored\"(\n" +
	"\x16DeleteWorkspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17DeleteWorkspaceResponse\"\x19\n" +
	"\x17ReclaimWorktreesRequest\"'\n" +
	"\x11ReclaimedWorktree\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"C\n" +
	"\bConflict\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05paths\x18\x02 \x03(\tR\x05paths\"g\n" +
	"\bDecision\x12*\n" +
	"\averdict\x18\x01 \x01(\x0e2\x10.mesh.v1.VerdictR\averdict\x12/\n" +
	"\tconflicts\x18\x02 \x03(\v2\x11.mesh.v1.ConflictR\tconflicts\"M\n" +
	"\x12CheckIntentRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05files\x18\x02 \x03(\tR\x05files\"P\n" +
	"\x15RegisterIntentRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05files\x18\x02 \x03(\tR\x05files\"d\n" +
	"\x16RegisterIntentResponse\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12-\n" +
	"\bdecision\x18\x02 \x01(\v2\x11.mesh.v1.DecisionR\bdecision\"\xd1\x01\n" +
	"\vPullRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12)\n" +
	"\x06status\x18\x06 \x01(\x0e2\x11.mesh.v1.PRStatusR\x06status\x12\x1a\n" +
	"\battempts\x18\a \x01(\x05R\battempts\"~\n" +
	"\x0fSubmitPRRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\";\n" +
	"\x0eListPRsRequest\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.mesh.v1.PRStatusR\x06status\"\x13\n" +
	"\x11PlanTrainsRequest\"/\n" +
	"\x05Train\x12&\n" +
	"\x03prs\x18\x01 \x03(\v2\x14.mesh.v1.PullRequestR\x03prs*\x87\x01\n" +
	"\x0fWorkspaceStatus\x12 \n" +
	"\x1cWORKSPACE_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17WORKSPACE_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15WORKSPACE_STATUS_DONE\x10\x02\x12\x1a\n" +
	"\x16WORKSPACE_STATUS_ERROR\x10\x03*G\n" +
	"\aVerdict\x12\x17\n" +
	"\x13VERDICT_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rVERDICT_CLEAR\x10\x01\x12\x10\n" +
	"\fVERDICT_WARN\x10\x02*\x80\x01\n" +
	"\bPRStatus\x12\x19\n" +
	"\x15PR_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PR_STATUS_QUEUED\x10\x01\x12\x17\n" +
	"\x13PR_STATUS_SUBMITTED\x10\x02\x12\x14\n" +
	"\x10PR_STATUS_MERGED\x10\x03\x12\x14\n" +
	"\x10PR_STATUS_FAILED\x10\x042\x95\x06\n" +
	"\vMeshService\x12>\n" +
	"\rRegisterAgent\x12\x1d.mesh.v1.RegisterAgentRequest\x1a\x0e.mesh.v1.Agent\x12F\n" +
	"\x0fCreateWorkspace\x12\x1f.mesh.v1.CreateWorkspaceRequest\x1a\x12.mesh.v1.Workspace\x12F\n" +
	"\x0eListWorkspaces\x12\x1e.mesh.v1.ListWorkspacesRequest\x1a\x12.mesh.v1.Workspace0\x01\x12F\n" +
	"\x0fFinishWorkspace\x12\x1f.mesh.v1.FinishWorkspaceRequest\x1a\x12.mesh.v1.Workspace\x12T\n" +
	"\x0fDeleteWorkspace\x12\x1f.mesh.v1.DeleteWorkspaceRequest\x1a .mesh.v1.DeleteWorkspaceResponse\x12R\n" +
	"\x10ReclaimWorktrees\x12 .mesh.v1.ReclaimWorktreesRequest\x1a\x1a.mesh.v1.ReclaimedWorktree0\x01\x12=\n" +
	"\vCheckIntent\x12\x1b.mesh.v1.CheckIntentRequest\x1a\x11.mesh.v1.Decision\x12Q\n" +
	"\x0eRegisterIntent\x12\x1e.mesh.v1.RegisterIntentRequest\x1a\x1f.mesh.v1.RegisterIntentResponse\x12:\n" +
	"\bSubmitPR\x12\x18.mesh.v1.SubmitPRRequest\x1a\x14.mesh.v1.PullRequest\x12:\n" +
	"\aListPRs\x12\x17.mesh.v1.ListPRsRequest\x1a\x14.mesh.v1.PullRequest0\x01\x12:\n" +
	"\n" +
	"PlanTrains\x12\x1a.mesh.v1.PlanTrainsRequest\x1a\x0e.mesh.v1.Train0\x01B4Z2github.com/AyushPramanik/mesh/proto/mesh/v1;meshv1b\x06proto3"

var (
	file_proto_mesh_v1_mesh_proto_rawDescOnce sync.Once
	file_proto_mesh_v1_mesh_proto_rawDescData []byte
)

func file_proto_mesh_v1_mesh_proto_rawDescGZIP() []byte {
	file_proto_mesh_v1_mesh_proto_rawDescOnce.Do(func() {
		file_proto_mesh_v1_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mesh_v1_mesh_proto_rawDesc), len(file_proto_mesh_v1_mesh_proto_rawDesc)))
	})
	return file_proto_mesh_v1_mesh_proto_rawDescData
}

var file_proto_mesh_v1_mesh_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_mesh_v1_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_mesh_v1_mesh_proto_goTypes = []any{
	(WorkspaceStatus)(0),            // 0: mesh.v1.WorkspaceStatus
	(Verdict)(0),                    // 1: mesh.v1.Verdict
	(PRStatus)(0),                   // 2: mesh.v1.PRStatus
	(*Agent)(nil),                   // 3: mesh.v1.Agent
	(*RegisterAgentRequest)(nil),    // 4: mesh.v1.RegisterAgentRequest
	(*Workspace)(nil),               // 5: mesh.v1.Workspace
	(*CreateWorkspaceRequest)(nil),  // 6: mesh.v1.CreateWorkspaceRequest
	(*ListWorkspacesRequest)(nil),   // 7: mesh.v1.ListWorkspacesRequest
	(*FinishWorkspaceRequest)(nil),  // 8: mesh.v1.FinishWorkspaceRequest
	(*DeleteWorkspaceRequest)(nil),  // 9: mesh.v1.DeleteWorkspaceRequest
	(*DeleteWorkspaceResponse)(nil), // 10: mesh.v1.DeleteWorkspaceResponse
	(*ReclaimWorktreesRequest)(nil), // 11: mesh.v1.ReclaimWorktreesRequest
	(*ReclaimedWorktree)(nil),       // 12: mesh.v1.ReclaimedWorktree
	(*Conflict)(nil),                // 13: mesh.v1.Conflict
	(*Decision)(nil),                // 14: mesh.v1.Decision
	(*CheckIntentRequest)(nil),      // 15: mesh.v1.CheckIntentRequest
	(*RegisterIntentRequest)(nil),   // 16: mesh.v1.RegisterIntentRequest
	(*RegisterIntentResponse)(nil),  // 17: mesh.v1.RegisterIntentResponse
	(*PullRequest)(nil),             // 18: mesh.v1.PullRequest
	(*SubmitPRRequest)(nil),         // 19: mesh.v1.SubmitPRRequest
	(*ListPRsRequest)(nil),          // 20: mesh.v1.ListPRsRequest
	(*PlanTrainsRequest)(nil),       // 21: mesh.v1.PlanTrainsRequest
	(*Train)(nil),                   // 22: mesh.v1.Train
}
var file_proto_mesh_v1_mesh_proto_depIdxs = []int32{
	0,  // 0: mesh.v1.Workspace.status:type_name -> mesh.v1.WorkspaceStatus
	1,  // 1: mesh.v1.Decision.verdict:type_name -> mesh.v1.Verdict
	13, // 2: mesh.v1.Decision.conflicts:type_name -> mesh.v1.Conflict
	14, // 3: mesh.v1.RegisterIntentResponse.decision:type_name -> mesh.v1.Decision
	2,  // 4: mesh.v1.PullRequest.status:type_name -> mesh.v1.PRStatus
	2,  // 5: mesh.v1.ListPRsRequest.status:type_name -> mesh.v1.PRStatus
	18, // 6: mesh.v1.Train.prs:type_name -> mesh.v1.PullRequest
	4,  // 7: mesh.v1.MeshService.RegisterAgent:input_type -> mesh.v1.RegisterAgentRequest
	6,  // 8: mesh.v1.MeshService.CreateWorkspace:input_type -> mesh.v1.CreateWorkspaceRequest
	7,  // 9: mesh.v1.MeshService.ListWorkspaces:input_type -> mesh.v1.ListWorkspacesRequest
	8,  // 10: mesh.v1.MeshService.FinishWorkspace:input_type -> mesh.v1.FinishWorkspaceRequest
	9,  // 11: mesh.v1.MeshService.DeleteWorkspace:input_type -> mesh.v1.DeleteWorkspaceRequest
	11, // 12: mesh.v1.MeshService.ReclaimWorktrees:input_type -> mesh.v1.ReclaimWorktreesRequest
	15, // 13: mesh.v1.MeshService.CheckIntent:input_type -> mesh.v1.CheckIntentRequest
	16, // 14: mesh.v1.MeshService.RegisterIntent:input_type -> mesh.v1.RegisterIntentRequest
	19, // 15: mesh.v1.MeshService.SubmitPR:input_type -> mesh.v1.SubmitPRRequest
	20, // 16: mesh.v1.MeshService.ListPRs:input_type -> mesh.v1.ListPRsRequest
	21, // 17: mesh.v1.MeshService.PlanTrains:input_type -> mesh.v1.PlanTrainsRequest
	3,  // 18: mesh.v1.MeshService.RegisterAgent:output_type -> mesh.v1.Agent
	5,  // 19: mesh.v1.MeshService.CreateWorkspace:output_type -> mesh.v1.Workspace
	5,  // 20: mesh.v1.MeshService.ListWorkspaces:output_type -> mesh.v1.Workspace
	5,  // 21: mesh.v1.MeshService.FinishWorkspace:output_type -> mesh.v1.Workspace
	10, // 22: mesh.v1.MeshService.DeleteWorkspace:output_type -> mesh.v1.DeleteWorkspaceResponse
	12, // 23: mesh.v1.MeshService.ReclaimWorktrees:output_type -> mesh.v1.ReclaimedWorktree
	14, // 24: mesh.v1.MeshService.CheckIntent:output_type -> mesh.v1.Decision
	17, // 25: mesh.v1.MeshService.RegisterIntent:output_type -> mesh.v1.RegisterIntentResponse
	18, // 26: mesh.v1.MeshService.SubmitPR:output_type -> mesh.v1.PullRequest
	18, // 27: mesh.v1.MeshService.ListPRs:output_type -> mesh.v1.PullRequest
	22, // 28: mesh.v1.MeshService.PlanTrains:output_type -> mesh.v1.Train
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_mesh_v1_mesh_proto_init() }
func file_proto_mesh_v1_mesh_proto_init() {
	if File_proto_mesh_v1_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mesh_v1_mesh_proto_rawDesc), len(file_proto_mesh_v1_mesh_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mesh_v1_mesh_proto_goTypes,
		DependencyIndexes: file_proto_mesh_v1_mesh_proto_depIdxs,
		EnumInfos:         file_proto_mesh_v1_mesh_proto_enumTypes,
		MessageInfos:      file_proto_mesh_v1_mesh_proto_msgTypes,
	}.Build()
	File_proto_mesh_v1_mesh_proto = out.File
	file_proto_mesh_v1_mesh_proto_goTypes = nil
	file_proto_mesh_v1_mesh_proto_depIdxs = nil
}
