// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package store

import (
	"context"
)

const getAgent = `-- name: GetAgent :one
SELECT id, name, registered_at FROM agents WHERE id = ?
`

func (q *Queries) GetAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgent, id)
	var i Agent
	err := row.Scan(&i.ID, &i.Name, &i.RegisteredAt)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, registered_at FROM agents ORDER BY registered_at ASC
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(&i.ID, &i.Name, &i.RegisteredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerAgent = `-- name: RegisterAgent :one
INSERT INTO agents (id, name)
VALUES (?, ?)
ON CONFLICT (id) DO UPDATE SET name = excluded.name
RETURNING id, name, registered_at
`

type RegisterAgentParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// Register an agent, or update its name if the id already exists. Idempotent so
// a reconnecting agent does not error.
func (q *Queries) RegisterAgent(ctx context.Context, arg RegisterAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, registerAgent, arg.ID, arg.Name)
	var i Agent
	err := row.Scan(&i.ID, &i.Name, &i.RegisteredAt)
	return i, err
}
