// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: intents.sql

package store

import (
	"context"
	"strings"
)

const addIntentFile = `-- name: AddIntentFile :exec
INSERT INTO intent_files (intent_id, path)
VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type AddIntentFileParams struct {
	IntentID string `json:"intent_id"`
	Path     string `json:"path"`
}

func (q *Queries) AddIntentFile(ctx context.Context, arg AddIntentFileParams) error {
	_, err := q.db.ExecContext(ctx, addIntentFile, arg.IntentID, arg.Path)
	return err
}

const createIntent = `-- name: CreateIntent :one
INSERT INTO intents (id, workspace_id)
VALUES (?, ?)
RETURNING id, workspace_id, status, created_at
`

type CreateIntentParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) CreateIntent(ctx context.Context, arg CreateIntentParams) (Intent, error) {
	row := q.db.QueryRowContext(ctx, createIntent, arg.ID, arg.WorkspaceID)
	var i Intent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const findOverlappingIntents = `-- name: FindOverlappingIntents :many
SELECT i.workspace_id, f.path
FROM intent_files f
JOIN intents i ON i.id = f.intent_id
WHERE i.status = 'active'
  AND i.workspace_id != ?1
  AND f.path IN (/*SLICE:paths*/?)
`

type FindOverlappingIntentsParams struct {
	WorkspaceID string   `json:"workspace_id"`
	Paths       []string `json:"paths"`
}

type FindOverlappingIntentsRow struct {
	WorkspaceID string `json:"workspace_id"`
	Path        string `json:"path"`
}

// Active intents owned by other workspaces that claim any of the given paths.
// This is the file-level overlap check at the heart of the conflict predictor.
func (q *Queries) FindOverlappingIntents(ctx context.Context, arg FindOverlappingIntentsParams) ([]FindOverlappingIntentsRow, error) {
	query := findOverlappingIntents
	var queryParams []interface{}
	queryParams = append(queryParams, arg.WorkspaceID)
	if len(arg.Paths) > 0 {
		for _, v := range arg.Paths {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:paths*/?", strings.Repeat(",?", len(arg.Paths))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:paths*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindOverlappingIntentsRow{}
	for rows.Next() {
		var i FindOverlappingIntentsRow
		if err := rows.Scan(&i.WorkspaceID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseIntent = `-- name: ReleaseIntent :exec
UPDATE intents SET status = 'released' WHERE id = ?
`

func (q *Queries) ReleaseIntent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, releaseIntent, id)
	return err
}

const releaseWorkspaceIntents = `-- name: ReleaseWorkspaceIntents :exec
UPDATE intents SET status = 'released' WHERE workspace_id = ?
`

func (q *Queries) ReleaseWorkspaceIntents(ctx context.Context, workspaceID string) error {
	_, err := q.db.ExecContext(ctx, releaseWorkspaceIntents, workspaceID)
	return err
}
