// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Agent struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	RegisteredAt string `json:"registered_at"`
}

type Intent struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Status      string `json:"status"`
	CreatedAt   string `json:"created_at"`
}

type IntentFile struct {
	IntentID string `json:"intent_id"`
	Path     string `json:"path"`
}

type PrQueue struct {
	ID          string  `json:"id"`
	WorkspaceID string  `json:"workspace_id"`
	Branch      string  `json:"branch"`
	Title       string  `json:"title"`
	Priority    int64   `json:"priority"`
	Status      string  `json:"status"`
	Attempts    int64   `json:"attempts"`
	LastError   *string `json:"last_error"`
	NextRetryAt *string `json:"next_retry_at"`
	SubmittedAt *string `json:"submitted_at"`
	CreatedAt   string  `json:"created_at"`
}

type Workspace struct {
	ID        string `json:"id"`
	AgentID   string `json:"agent_id"`
	Branch    string `json:"branch"`
	Path      string `json:"path"`
	Status    string `json:"status"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}
