// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pr_queue.sql

package store

import (
	"context"
)

const deletePR = `-- name: DeletePR :exec
DELETE FROM pr_queue WHERE id = ?
`

func (q *Queries) DeletePR(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePR, id)
	return err
}

const enqueuePR = `-- name: EnqueuePR :one
INSERT INTO pr_queue (id, workspace_id, branch, title, priority)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (branch) DO UPDATE SET branch = excluded.branch
RETURNING id, workspace_id, branch, title, priority, status, attempts, last_error, submitted_at, created_at
`

type EnqueuePRParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Branch      string `json:"branch"`
	Title       string `json:"title"`
	Priority    int64  `json:"priority"`
}

// Submit a PR to the queue. The branch is the dedupe key: submitting a branch
// that is already queued is a no-op that returns the existing row unchanged.
func (q *Queries) EnqueuePR(ctx context.Context, arg EnqueuePRParams) (PrQueue, error) {
	row := q.db.QueryRowContext(ctx, enqueuePR,
		arg.ID,
		arg.WorkspaceID,
		arg.Branch,
		arg.Title,
		arg.Priority,
	)
	var i PrQueue
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Branch,
		&i.Title,
		&i.Priority,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.SubmittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPR = `-- name: GetPR :one
SELECT id, workspace_id, branch, title, priority, status, attempts, last_error, submitted_at, created_at FROM pr_queue WHERE id = ?
`

func (q *Queries) GetPR(ctx context.Context, id string) (PrQueue, error) {
	row := q.db.QueryRowContext(ctx, getPR, id)
	var i PrQueue
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Branch,
		&i.Title,
		&i.Priority,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.SubmittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPRByBranch = `-- name: GetPRByBranch :one
SELECT id, workspace_id, branch, title, priority, status, attempts, last_error, submitted_at, created_at FROM pr_queue WHERE branch = ?
`

func (q *Queries) GetPRByBranch(ctx context.Context, branch string) (PrQueue, error) {
	row := q.db.QueryRowContext(ctx, getPRByBranch, branch)
	var i PrQueue
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Branch,
		&i.Title,
		&i.Priority,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.SubmittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPRsByStatus = `-- name: ListPRsByStatus :many
SELECT id, workspace_id, branch, title, priority, status, attempts, last_error, submitted_at, created_at FROM pr_queue
WHERE status = ?
ORDER BY priority DESC, created_at ASC
`

// Scheduler scan order: highest priority first, then oldest submission.
func (q *Queries) ListPRsByStatus(ctx context.Context, status string) ([]PrQueue, error) {
	rows, err := q.db.QueryContext(ctx, listPRsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrQueue{}
	for rows.Next() {
		var i PrQueue
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Branch,
			&i.Title,
			&i.Priority,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.SubmittedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPRSubmitted = `-- name: MarkPRSubmitted :exec
UPDATE pr_queue
SET status = 'submitted', submitted_at = datetime('now')
WHERE id = ?
`

func (q *Queries) MarkPRSubmitted(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markPRSubmitted, id)
	return err
}

const recordPRFailure = `-- name: RecordPRFailure :exec
UPDATE pr_queue
SET status = 'failed', attempts = attempts + 1, last_error = ?
WHERE id = ?
`

type RecordPRFailureParams struct {
	LastError *string `json:"last_error"`
	ID        string  `json:"id"`
}

// Record a failed submission attempt for exponential-backoff retry.
func (q *Queries) RecordPRFailure(ctx context.Context, arg RecordPRFailureParams) error {
	_, err := q.db.ExecContext(ctx, recordPRFailure, arg.LastError, arg.ID)
	return err
}

const setPRStatus = `-- name: SetPRStatus :exec
UPDATE pr_queue SET status = ? WHERE id = ?
`

type SetPRStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) SetPRStatus(ctx context.Context, arg SetPRStatusParams) error {
	_, err := q.db.ExecContext(ctx, setPRStatus, arg.Status, arg.ID)
	return err
}
