// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	AddIntentFile(ctx context.Context, arg AddIntentFileParams) error
	CreateIntent(ctx context.Context, arg CreateIntentParams) (Intent, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeletePR(ctx context.Context, id string) error
	DeleteWorkspace(ctx context.Context, id string) error
	// Submit a PR to the queue. The branch is the dedupe key: submitting a branch
	// that is already queued is a no-op that returns the existing row unchanged.
	EnqueuePR(ctx context.Context, arg EnqueuePRParams) (PrQueue, error)
	// Active intents owned by other workspaces that claim any of the given paths.
	// This is the file-level overlap check at the heart of the conflict predictor.
	FindOverlappingIntents(ctx context.Context, arg FindOverlappingIntentsParams) ([]FindOverlappingIntentsRow, error)
	GetAgent(ctx context.Context, id string) (Agent, error)
	GetPR(ctx context.Context, id string) (PrQueue, error)
	GetPRByBranch(ctx context.Context, branch string) (PrQueue, error)
	GetWorkspace(ctx context.Context, id string) (Workspace, error)
	ListAgents(ctx context.Context) ([]Agent, error)
	// Queued PRs eligible to process now: never deferred, or past their backoff.
	// Same scan order as ListPRsByStatus.
	ListDuePRs(ctx context.Context) ([]PrQueue, error)
	// Scheduler scan order: highest priority first, then oldest submission.
	ListPRsByStatus(ctx context.Context, status string) ([]PrQueue, error)
	ListWorkspaces(ctx context.Context) ([]Workspace, error)
	ListWorkspacesByAgent(ctx context.Context, agentID string) ([]Workspace, error)
	ListWorkspacesByStatus(ctx context.Context, status string) ([]Workspace, error)
	MarkPRSubmitted(ctx context.Context, id string) error
	// Terminally fail a PR (permanent error or retries exhausted).
	RecordPRFailure(ctx context.Context, arg RecordPRFailureParams) error
	// Register an agent, or update its name if the id already exists. Idempotent so
	// a reconnecting agent does not error.
	RegisterAgent(ctx context.Context, arg RegisterAgentParams) (Agent, error)
	ReleaseIntent(ctx context.Context, id string) error
	ReleaseWorkspaceIntents(ctx context.Context, workspaceID string) error
	// Defer a PR after a transient failure: back to queued, attempt counted, and
	// not retried until now + the given SQLite modifier (e.g. '+8 seconds').
	RequeuePR(ctx context.Context, arg RequeuePRParams) error
	SetPRStatus(ctx context.Context, arg SetPRStatusParams) error
	SetWorkspaceStatus(ctx context.Context, arg SetWorkspaceStatusParams) error
}

var _ Querier = (*Queries)(nil)
