// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeletePR(ctx context.Context, id string) error
	DeleteWorkspace(ctx context.Context, id string) error
	// Submit a PR to the queue. The branch is the dedupe key: submitting a branch
	// that is already queued is a no-op that returns the existing row unchanged.
	EnqueuePR(ctx context.Context, arg EnqueuePRParams) (PrQueue, error)
	GetAgent(ctx context.Context, id string) (Agent, error)
	GetPR(ctx context.Context, id string) (PrQueue, error)
	GetPRByBranch(ctx context.Context, branch string) (PrQueue, error)
	GetWorkspace(ctx context.Context, id string) (Workspace, error)
	ListAgents(ctx context.Context) ([]Agent, error)
	// Scheduler scan order: highest priority first, then oldest submission.
	ListPRsByStatus(ctx context.Context, status string) ([]PrQueue, error)
	ListWorkspaces(ctx context.Context) ([]Workspace, error)
	ListWorkspacesByAgent(ctx context.Context, agentID string) ([]Workspace, error)
	ListWorkspacesByStatus(ctx context.Context, status string) ([]Workspace, error)
	MarkPRSubmitted(ctx context.Context, id string) error
	// Record a failed submission attempt for exponential-backoff retry.
	RecordPRFailure(ctx context.Context, arg RecordPRFailureParams) error
	// Register an agent, or update its name if the id already exists. Idempotent so
	// a reconnecting agent does not error.
	RegisterAgent(ctx context.Context, arg RegisterAgentParams) (Agent, error)
	SetPRStatus(ctx context.Context, arg SetPRStatusParams) error
	SetWorkspaceStatus(ctx context.Context, arg SetWorkspaceStatusParams) error
}

var _ Querier = (*Queries)(nil)
