// Package store is the daemon's persistent local state: agent registry,
// workspace lifecycle, and the PR queue. The query layer is generated by sqlc
// from internal/store/queries (run `make sqlc` after editing the SQL); this
// file hand-writes only the connection and migration glue that sqlc does not.
//
// The driver is modernc.org/sqlite — a pure-Go SQLite, no CGO — matching the
// project's no-CGO stance (see CLAUDE.md tech stack). Because the queries are
// plain SQL with sqlc targeting both engines, moving to Postgres for the hosted
// tier is a driver swap, not a rewrite.
package store

import (
	"context"
	"database/sql"
	_ "embed"
	"fmt"
	"strings"

	_ "modernc.org/sqlite"
)

//go:embed schema.sql
var schema string

// Store owns the database handle and embeds the generated *Queries so callers
// have one type for both raw lifecycle (Close, Tx) and typed queries.
type Store struct {
	*Queries
	db *sql.DB
}

// Open opens (creating if necessary) the SQLite database at dsn and applies the
// schema. dsn is a file path; pass ":memory:" for an ephemeral database in
// tests. Foreign keys are enforced for every connection in the pool.
func Open(ctx context.Context, dsn string) (*Store, error) {
	// _pragma applies per-connection; these must be set on every connection in
	// the pool, not just the first, hence DSN parameters rather than one-off
	// PRAGMA statements. foreign_keys enforces referential integrity;
	// busy_timeout makes a connection wait out a lock instead of failing
	// immediately with SQLITE_BUSY — essential because the daemon writes from
	// the queue goroutine while serving reads to gRPC and the dashboard. WAL
	// lets readers and a writer proceed concurrently and survives crashes
	// better than the default rollback journal; synchronous(NORMAL) is the
	// safe, fast pairing with WAL. WAL is a file-only mode, so it is omitted
	// for the in-memory database used in tests.
	pragmas := []string{"foreign_keys(1)", "busy_timeout(5000)"}
	if dsn != ":memory:" {
		pragmas = append(pragmas, "journal_mode(WAL)", "synchronous(NORMAL)")
	}
	db, err := sql.Open("sqlite", dsn+"?_pragma="+strings.Join(pragmas, "&_pragma="))
	if err != nil {
		return nil, fmt.Errorf("store.Open: %w", err)
	}
	if dsn == ":memory:" {
		// A bare in-memory database is private to a single connection; pin the
		// pool to one so the schema and data are visible across all queries.
		db.SetMaxOpenConns(1)
	}
	if err := db.PingContext(ctx); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("store.Open: ping: %w", err)
	}
	if _, err := db.ExecContext(ctx, schema); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("store.Open: apply schema: %w", err)
	}
	return &Store{Queries: New(db), db: db}, nil
}

// Tx runs fn inside a database transaction, committing on success and rolling
// back on error or panic. The *Queries passed to fn is scoped to the
// transaction.
func (s *Store) Tx(ctx context.Context, fn func(*Queries) error) (err error) {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("store.Tx: begin: %w", err)
	}
	defer func() {
		if p := recover(); p != nil {
			_ = tx.Rollback()
			panic(p)
		}
		if err != nil {
			_ = tx.Rollback()
		}
	}()

	if err = fn(s.WithTx(tx)); err != nil {
		return err
	}
	if err = tx.Commit(); err != nil {
		return fmt.Errorf("store.Tx: commit: %w", err)
	}
	return nil
}

// Ping verifies the database connection is alive. It backs the daemon's
// readiness probe.
func (s *Store) Ping(ctx context.Context) error { return s.db.PingContext(ctx) }

// Close releases the database handle.
func (s *Store) Close() error { return s.db.Close() }
