// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package store

import (
	"context"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, agent_id, branch, path)
VALUES (?, ?, ?, ?)
RETURNING id, agent_id, branch, path, status, created_at, updated_at
`

type CreateWorkspaceParams struct {
	ID      string `json:"id"`
	AgentID string `json:"agent_id"`
	Branch  string `json:"branch"`
	Path    string `json:"path"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace,
		arg.ID,
		arg.AgentID,
		arg.Branch,
		arg.Path,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Branch,
		&i.Path,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = ?
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspace, id)
	return err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, agent_id, branch, path, status, created_at, updated_at FROM workspaces WHERE id = ?
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Branch,
		&i.Path,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, agent_id, branch, path, status, created_at, updated_at FROM workspaces ORDER BY created_at ASC
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Branch,
			&i.Path,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByAgent = `-- name: ListWorkspacesByAgent :many
SELECT id, agent_id, branch, path, status, created_at, updated_at FROM workspaces WHERE agent_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListWorkspacesByAgent(ctx context.Context, agentID string) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacesByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Branch,
			&i.Path,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByStatus = `-- name: ListWorkspacesByStatus :many
SELECT id, agent_id, branch, path, status, created_at, updated_at FROM workspaces WHERE status = ? ORDER BY created_at ASC
`

func (q *Queries) ListWorkspacesByStatus(ctx context.Context, status string) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Branch,
			&i.Path,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorkspaceStatus = `-- name: SetWorkspaceStatus :exec
UPDATE workspaces
SET status = ?, updated_at = datetime('now')
WHERE id = ?
`

type SetWorkspaceStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) SetWorkspaceStatus(ctx context.Context, arg SetWorkspaceStatusParams) error {
	_, err := q.db.ExecContext(ctx, setWorkspaceStatus, arg.Status, arg.ID)
	return err
}
